import{a as R,S as P,i as n}from"./assets/vendor-Cm9gDZN8.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&i(u)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();const m=15,$="52399485-abaa9cbef55c5a94206dd148e",B="https://pixabay.com/api/";async function w(e,o=1){if(!String(e).trim())throw new Error("Empty query");try{return(await R.get(B,{params:{key:$,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:m},timeout:1e4})).data}catch(i){throw i}}const L=document.querySelector(".gallery"),h=document.querySelector(".load-more"),d=document.querySelector(".loader"),M=new P(".gallery a",{captionsData:"alt",captionDelay:250});function S(e){if(!Array.isArray(e)||e.length===0)return;const o=e.map(({webformatURL:r,largeImageURL:i,tags:t,likes:s,views:u,comments:A,downloads:E})=>`
      <li class="gallery-item" style="height: 200px;">
        <a href="${i}">
          <img class="gallery-img" src="${r}" alt="${t}" loading="lazy" />
        </a>
        <ul class="stat-list">
          <li class="stat-item"><span class="stat-title">Likes</span>${s}</li>
          <li class="stat-item"><span class="stat-title">Views</span>${u}</li>
          <li class="stat-item"><span class="stat-title">Comments</span>${A}</li>
          <li class="stat-item"><span class="stat-title">Downloads</span>${E}</li>
        </ul>
      </li>
    `).join("");L.insertAdjacentHTML("beforeend",o),M.refresh()}function x(){L.innerHTML=""}function b(){d&&d.classList.remove("hidden")}function q(){d&&d.classList.add("hidden")}function v(){h&&h.classList.remove("hidden")}function c(){h&&h.classList.add("hidden")}const y=document.querySelector(".form"),H=y.querySelector('input[name="search-text"]'),p=document.querySelector(".load-more");let f="",g=1,a=0,l=0;y&&y.addEventListener("submit",I);p&&(p.addEventListener("click",O),c());async function I(e){e.preventDefault();const o=H.value.trim();if(!o){n.warning({title:"Warning",message:"Please enter a search query!",position:"topRight"});return}f=o,g=1,a=0,l=0,x(),c(),b();try{const r=await w(f,g);if(a=r.totalHits||0,!Array.isArray(r.hits)||r.hits.length===0){n.error({title:"Sorry",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}S(r.hits),l+=r.hits.length,n.success({title:"Success",message:`Hooray! We found ${a} images.`,position:"topRight"}),l<a&&r.hits.length===m?v():(c(),l>=a&&n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(r){console.error(r),n.error({title:"Error",message:r.message||"Something went wrong. Please try again later.",position:"topRight"})}finally{q()}}async function O(){if(f){g+=1,b();try{const e=await w(f,g);if(!Array.isArray(e.hits)||e.hits.length===0){c(),n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}S(e.hits),l+=e.hits.length;const o=document.querySelector(".gallery .gallery-item");if(o){const{height:t}=o.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}const r=l,i=e.totalHits??a;r>=i?(c(),n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):e.hits.length<m?c():v()}catch(e){console.error(e),n.error({title:"Error",message:e.message||"Something went wrong while loading more.",position:"topRight"})}finally{q()}}}
//# sourceMappingURL=index.js.map
